routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'web', 'prefix' => '/'], function () {
    Auth::routes();
    Route::group(['middleware' => 'auth'], function() {
        Route::get('home', 'HomeController@index')->name('home');
        Route::resource('subject', 'SubjectController');
        Route::get('subject/student-list/{subject}', 'SubjectController@studentList')->name('subject.student-list');
        Route::resource('enroll-request', 'EnrollRequestController');
        Route::resource('exam', 'ExamController');
        Route::get('exam/change-status/{exam}', 'ExamController@changeStatus')->name('exam.change-status');
        Route::resource('notice', 'NoticeController');
        Route::resource('student', 'StudentController');
    });

    Route::group(['middleware' => 'admin_auth'], function () {
        Route::resource('teacher', 'TeacherController');
        Route::post('subject/{subject}/assign-teacher', 'SubjectController@assignTeacher');
    });

    Route::group(['middleware' => 'student_auth'], function () {
        Route::get('unenrolled-subjects', 'SubjectController@unenrolledSubjects')->name('unenrolled-subjects');
        Route::get('take-exam/{exam}', 'ExamController@takeExam')->name('exam.take-exam');
        Route::post('store-answer/{exam}', 'ExamController@storeAnswer')->name('exam.store-answer');
    });

    Route::group(['middleware' => 'teacher_auth'], function () {
        Route::resource('exam-question', 'ExamQuestionController');
        Route::get('exam/{exam}/student', 'ExamController@student')->name('exam.show-student');
    });
});

app/Models/Exam.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Exam extends Model
{
    protected $guarded = ['id'];

    public function subjectTeacher()
    {
        return $this->belongsTo(SubjectTeacher::class);
    }

    public function questions()
    {
        return $this->hasMany(ExamQuestion::class);
    }

    public function students()
    {
        return $this->hasMany(ExamStudent::class);
    }

    public function isEligibleNow(Student $student)
    {
        $student_exam = $this->students()->where('student_id', $student->id)->first();
        if ($student_exam) {
            $created_before = $student_exam->created_at->diffInMinutes(Carbon::now());
            return $created_before <= $this->time;
        }
        return true;
    }

    public function scopePublished($query)
    {
        return $query->where('is_publish', true);
    }

    public function createQuestionAnswer(Student $student)
    {
        $student_exam = $this->students()->where('student_id', $student->id)->first();
        if ($student_exam) return $student_exam;
        return $this->students()->create([
            'exam_id' => $this->id, 
            'student_id' => $student->id
        ]);
    }

    public function calculateMark(Student $student)
    {
        $qustions = $this->questions;
        $mark = 0;

        foreach($qustions as $question) {
            $answer = $question->answers()->where('student_id', $student->id)->first();
            $mark += $answer->mark;
        }
        return $mark;
    }
}

app/Models/Teacher.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
class Teacher extends Model
{
    protected $guarded = ['id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function subjectStudent()
    {
        return $this->hasManyThrough(SubjectStudent::class, SubjectTeacher::class);
    }

    public function subjectTeacher()
    {
        return $this->hasMany(SubjectTeacher::class);
    }
}

app/Http/Controllers/ExamController.php
<?php namespace App\Http\Controllers;

use App\Models\Exam;
use App\Models\QuestionAnswer;
use Illuminate\Http\Request;
use DB;
class ExamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (auth()->user()->isTeacher()) {
            $teacher = auth()->user()->teacher;
            $exams = Exam::whereHas('subjectTeacher', function ($query) use ($teacher) {
                return $query->where('teacher_id', $teacher->id);
            })->with('subjectTeacher.subject')->paginate(10);
            return teacherView('exam.index', compact('exams'));
        } elseif (auth()->user()->isStudent()) {
            $student = auth()->user()->student;
            $exams = Exam::published()->whereHas('subjectTeacher', function ($query) use ($student) {
                return $query->whereHas('subjectStudent', function ($query2) use ($student) {
                    return $query2->where('student_id', $student->id);
                });
            })->with([
                'subjectTeacher.subject', 
                'subjectTeacher.teacher.user',
                'students' => function ($query) use ($student) {
                    return $query->where('student_id', $student->id);
                }])->get();
            return studentView('exam.index', compact('exams'));
        }
        return redirect('home');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (auth()->user()->isTeacher()) {
            $teacher = auth()->user()->teacher;
            $subjects = $teacher->load('subjectTeacher.subject')->subjectTeacher;
            
            return teacherView('exam.create', compact('subjects'));
        }
        return redirect('home');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (auth()->user()->isTeacher()) {
            $this->validate($request, [
                'name' => 'required',
                'subject' => 'required',
                'time' => 'required'
            ]);
            
            Exam::create([
                'name' => $request->name,
                'subject_teacher_id' => $request->subject,
                'time' => $request->time
            ]);

            return redirect()->route('exam.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function show(Exam $exam)
    {
        if (auth()->user()->isTeacher()) {
            $exam = $exam->load(['questions.options', 'subjectTeacher.subject', 'students']);
            return teacherView('exam.show', compact('exam'));
        } elseif (auth()->user()->isStudent()) {
            $student = auth()->user()->student;
            $exam = $exam->load(['subjectTeacher.subject', 'students' => function($query) use ($student) {
                return $query->where('student_id', $student->id);
            }]);
            return studentView('exam.show', compact('exam', 'student'));
        }
        return redirect('home');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function edit(Exam $exam)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Exam $exam)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Exam  $exam
     * @return \Illuminate\Http\Response
     */
    public function destroy(Exam $exam)
    {
        //
    }

    public function changeStatus(Exam $exam)
    {
        if (auth()->user()->isStudent()) return redirect()->route('home');
        $data = ['is_publish' => !$exam->is_publish];
        $exam->update($data);
        return redirect()->back();
    }

    public function takeExam(Exam $exam)
    {
        if (auth()->user()->isStudent()) {
            $student = auth()->user()->student;
            if ($exam->isEligibleNow($student)) {
                $exam->load('questions.options');
                $exam_student = $exam->createQuestionAnswer($student);
                $exam_end_time = $exam_student->created_at->addMinutes($exam->time);
                return studentView('exam.take-exam', compact('exam', 'exam_student', 'exam_end_time'));
            } 
            return redirect('home');
        }

        return redirect('home');
    }

    public function storeAnswer(Request $request, Exam $exam)
    {
        if (auth()->user()->isStudent()) {
            DB::transaction(function() use ($request, $exam) {
                $student = auth()->user()->student;
                $exam_student = $request->exam_student;
                $questions = $exam->load('questions.options')->questions;
                foreach($questions as $question) {
                    $question_answer = QuestionAnswer::where([
                        'exam_question_id' => $question->id,
                        'student_id' => $student->id
                    ])->first();
                    if (!$request->has('question_answer_'.$question->id) && !$question_answer) {
                        QuestionAnswer::create([
                            'exam_question_id' => $question->id,
                            'student_id' => $student->id
                        ]);
                    } else {
                        $answer = $request['question_answer_'.$question->id];
                        $currect_answer = $question->options->where('is_answer', true)->first()->id;
                        if (!$question_answer) {
                            QuestionAnswer::create([
                                'exam_question_id' => $question->id,
                                'student_id' => $student->id,
                                'option_id' => $answer,
                                'is_currect' => $answer == $currect_answer,
                                'mark' => $answer == $currect_answer ? $question->mark : 0
                            ]);
                        } else {
                            $question_answer->update([
                                'exam_question_id' => $question->id,
                                'student_id' => $student->id,
                                'option_id' => $answer,
                                'is_currect' => $answer == $currect_answer,
                                'mark' => $answer == $currect_answer ? $question->mark : 0
                            ]);
                        }
                    }
                }
            });

            return redirect()->route('exam.show', $exam->id);
        }
        return redirect('home');
    }

    public function student(Exam $exam)
    {
        $exam->load('students.student.user');
        return teacherView('exam.show-student', compact('exam'));
    }
}

app/Http/Controllers/TeacherController.php
<?php namespace App\Http\Controllers;

use Illuminate\Http\Request;
use TSC\Repositories\TeacherRepository;
use App\Models\Teacher;
class TeacherController extends Controller
{

    public function __construct(TeacherRepository $teacherRepository) 
    {
        $this->teacherRepository = $teacherRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teachers = $this->teacherRepository->getAllWithUser();
        return adminView('teacher.index', compact('teachers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return adminView('teacher.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|min:3',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|confirmed|string'
        ]);

        $teacher = $this->teacherRepository->create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password)
        ]);

        return redirect()->route('teacher.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function show(Teacher $teacher)
    {
        if (auth()->user()->isAdmin()) {
            $teacher->load(['user', 'subjectTeacher' => function ($query) {
                return $query->with(['subject', 'subjectStudent', 'enrollRequest' => function ($query2) {
                    return $query2->status(constants('ENROLL_STATUS')['Pending']);
                }]);
            }]);

            return adminView('teacher.show', compact('teacher'));
        }
        return redirect('home');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  $teacher
     * @return \Illuminate\Http\Response
     */
    public function edit($teacher)
    {
        $teacher = $this->teacherRepository->findWithUser($teacher);
        return adminView('teacher.edit', compact('teacher'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  $teacher
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $teacher)
    {
        $teacher = $this->teacherRepository->findWithUser($teacher);
        $this->validate($request, [
            'name' => 'required|string|min:3',
            'email' => "required|email|unique:users,email,".$teacher->user->id.",id",
            'password' => 'confirmed'
        ]);
        
        $data = [
            'name' => $request->name,
            'email' => $request->email,
        ];
        if(!empty($request->password)) $data['password'] = bcrypt($request->password);
        $this->teacherRepository->update($teacher, $data);
        return redirect()->route('teacher.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Teacher  $teacher
     * @return \Illuminate\Http\Response
     */
    public function destroy(Teacher $teacher)
    {
        //
    }
}

resources/views/teacher/exam/add-question.blade.php
@extends('layouts.teacher.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Add Question to {{ $exam->name}}</h3>
                </div>

                <div class="panel-body">
                    <form action="{{ route('exam-question.store') }}" method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label>Question</label>
                            <input type="text" class="form-control" name="question" value="{{ old('question') }}" required placeholder="Add Question Statement">
                            @if ($errors->has('question'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('question') }}</strong>
                                </span>
                            @endif
                        </div>
                        
                        <div class="form-group">
                            <label>Option A</label>
                            <input type="text" class="form-control" name="option_1" value="{{ old('option_1') }}" required>
                            @if ($errors->has('option_1'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('option_1') }}</strong>
                                </span>
                            @endif
                            <br>
                            <label>Image for Option A (optional)</label>
                            <input type="file" class="form-control" name="option_image_1">
                            @if ($errors->has('option_image_1'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('option_image_1') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label>Option B</label>
                            <input type="text" class="form-control" name="option_2" value="{{ old('option_2') }}" required>
                            @if ($errors->has('option_2'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('option_2') }}</strong>
                                </span>
                            @endif
                            <br>
                            <label>Image for Option B (optional)</label>
                            <input type="file" class="form-control" name="option_image_2">
                            @if ($errors->has('option_image_2'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('option_image_2') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label>Option C</label>
                            <input type="text" class="form-control" name="option_3" value="{{ old('option_3') }}" required>
                            @if ($errors->has('option_3'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('option_3') }}</strong>
                                </span>
                            @endif
                            <br>
                            <label>Image for Option C (optional)</label>
                            <input type="file" class="form-control" name="option_image_3">
                            @if ($errors->has('option_image_3'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('option_image_3') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label>Option D</label>
                            <input type="text" class="form-control" name="option_4" value="{{ old('option_4') }}" required>
                            @if ($errors->has('option_4'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('option_4') }}</strong>
                                </span>
                            @endif
                            <br>
                            <label>Image for Option D (optional)</label>
                            <input type="file" class="form-control" name="option_image_4">
                            @if ($errors->has('option_image_4'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('option_image_4') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label>Answer</label>
                            <select name="answer" class="form-control">
                                <option value="1">A</option>
                                <option value="2">B</option>
                                <option value="3">C</option>
                                <option value="4">D</option>
                            </select>
                            @if ($errors->has('answer'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('answer') }}</strong>
                                </span>
                            @endif
                        </div>
                        <input type="hidden" name="exam_id" value="{{request('exam_id')}}">
                        <div class="form-group">
                            <label>Mark</label>
                            <input type="number" class="form-control" min="1" name="mark" value="{{ old('mark') || 1 }}" required>
                            @if ($errors->has('mark'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('mark') }}</strong>
                                </span>
                            @endif
                        </div>
                        <input type="submit" class="btn btn-primary" value="Add Question">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/teacher/exam/edit-question.blade.php
@extends('layouts.teacher.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Edit Question</h3>
                </div>

                <div class="panel-body">
                    <form action="{{ route('exam-question.update', ['examQuestion' => $examQuestion->id]) }}" method="POST" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="PUT">
                        <div class="form-group">
                            <label>Question</label>
                            <input type="text" class="form-control" name="question" value="{{ old('question') ?: $examQuestion->question_statement }}" required placeholder="Add Question Statement">
                            @if ($errors->has('question'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('question') }}</strong>
                                </span>
                            @endif
                        </div>

                        <?php 
                            $alphabets = range('A', 'Z');
                            $image_url_prefix = URL::to('/img/exam_questions/');
                        ?>
                        @foreach($examQuestion->options as $count => $option)
                        <div class="form-group">
                            <label>Option {{$alphabets[$count]}}</label>
                            <input type="text" class="form-control" name="option_{{$count+1}}" value="{{ old('option_'.$count+1) ?: $option->option_statement }}" required>
                            @if ($errors->has('option_'. $count+1))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('option_'. $count+1) }}</strong>
                                </span>
                            @endif
                            <br>

                            @if ($option->option_image)
                            <img src="{{$image_url_prefix . '/' .$option->option_image}}" 
                                 alt="Option Image" style="height:150px;"><br>
                            @endif

                            <label>Image for Option {{$alphabets[$count]}} (optional)</label>
                            <input type="file" class="form-control" name="option_image_{{$count+1}}">
                            @if ($errors->has('option_image_'.$count+1))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('option_image_'.$count+1) }}</strong>
                                </span>
                            @endif
                        </div>
                        @endforeach

                        <div class="form-group">
                            <label>Answer</label>
                            <select name="answer" class="form-control">
                                @foreach($examQuestion->options as $count => $option)
                                <option value="{{$count+1}}" {{ $option->is_answer ? 'selected' : ''}}>{{$alphabets[$count]}}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('answer'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('answer') }}</strong>
                                </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label>Mark</label>
                            <input type="number" class="form-control" min="1" name="mark" value="{{ old('mark') ?: $examQuestion->mark }}" required>
                            @if ($errors->has('mark'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('mark') }}</strong>
                                </span>
                            @endif
                        </div>
                        <input type="submit" class="btn btn-primary" value="Edit Question">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/teacher/exam/show-student.blade.php
@extends('layouts.teacher.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 style="display:inline;">Student List for {{$exam->name}} </h3>
                </div>

                <div class="panel-body">
                    <table class="table table-bordered table-hover table-striped table-responsive">
                        <thead>
                        <tr>
                            <th>ID.</th>
                            <th>Student Name</th>
                            <th>Student Email</th>
                            <th>Student ID</th>
                            <th>Mark</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($exam->students as $student)
                        <tr>
                            <td>{{$student->student->id}}</td>
                            <td>{{$student->student->user->name}}</td>
                            <td>{{$student->student->user->email}}</td>
                            <td>{{$student->student->user->student_id}}</td>
                            <td>{{$exam->calculateMark($student->student)}}</td>
                        </tr>
                        @empty
                        <tr style="text-align:center;">
                            <td colspan=5><h4>No Student Found</h4></td>
                        </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/teacher/exam/show.blade.php
@extends('layouts.teacher.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 style="display:inline;">{{$exam->name}}</h3>
                    @if (!$exam->is_publish)
                        <a  href="{{route('exam-question.create', ['exam_id' => $exam->id])}}" class="btn btn-primary pull-right">Add Question</a>
                    @endif
                    <a  href="{{route('exam.change-status', ['exam_id' => $exam->id])}}"
                        class="btn pull-right {{$exam->is_publish ? 'btn-danger' : 'btn-success'}}">
                        {{$exam->is_publish ? 'Unpublish' : 'Publish'}}
                    </a>
                </div>

                <div class="panel-body">
                    <h4>Name: {{ $exam->name }}</h4>
                    <h4>Time: <code>{{ $exam->time }} Min(s)</code></h4>
                    <h4>Subject: {{$exam->subjectTeacher->subject->name}}</h4>
                    <h4>Total Question: {{$exam->questions->count()}}</h4>
                    <h4>Total Marks: {{$exam->questions->sum('mark')}}</h4>
                    <h4>Published: <code>{{$exam->is_publish ? 'Yes' : 'No'}}</code></h4>
                </div>
            </div>
        </div>

        <div class="col-md-10 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 style="display:inline;">Questions</h3>
                </div>

                <div class="panel-body">
                    <?php 
                        $alphabet = range('a', 'z'); 
                        $image_url_prefix = URL::to('/img/exam_questions/');
                    ?>
                    @foreach($exam->questions as $key => $question)
                        <h3>
                            {{$key + 1}}) {{$question->question_statement}} <span class="pull-right">{{$question->mark}}</span>
                            @if (!$exam->is_publish)
                            <a href="{{route('exam-question.edit', ['exam-qustion' => $question->id])}}" class="btn btn-primary pull-right">Edit</a>
                            @endif
                        </h3>
                        @foreach($question->options as $count => $option)
                            <h4 style="{{$option->is_answer ? 'color: green; font-weight:600;' : ''}}">{{$alphabet[$count]}}) {{$option->option_statement}}</h4> 
                            @if($option->option_image)
                            <img src="{{$image_url_prefix . '/' .$option->option_image}}" 
                                 alt="Option Image" style="height:150px;">
                            @endif
                        @endforeach
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@endsection