routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'web', 'prefix' => '/'], function () {
    Auth::routes();
    Route::group(['middleware' => 'auth'], function() {
        Route::get('home', 'HomeController@index')->name('home');
        Route::resource('subject', 'SubjectController');
        Route::get('subject/student-list/{subject}', 'SubjectController@studentList')->name('subject.student-list');
        Route::resource('enroll-request', 'EnrollRequestController');
        Route::resource('exam', 'ExamController');
        Route::get('exam/change-status/{exam}', 'ExamController@changeStatus')->name('exam.change-status');
        Route::resource('notice', 'NoticeController');
        Route::resource('student', 'StudentController');
    });

    Route::group(['middleware' => 'admin_auth'], function () {
        Route::resource('teacher', 'TeacherController');
        Route::post('subject/{subject}/assign-teacher', 'SubjectController@assignTeacher');
    });

    Route::group(['middleware' => 'student_auth'], function () {
        Route::get('unenrolled-subjects', 'SubjectController@unenrolledSubjects')->name('unenrolled-subjects');
        Route::get('take-exam/{exam}', 'ExamController@takeExam')->name('exam.take-exam');
        Route::post('store-answer/{exam}', 'ExamController@storeAnswer')->name('exam.store-answer');
    });

    Route::group(['middleware' => 'teacher_auth'], function () {
        Route::resource('exam-question', 'ExamQuestionController');
        Route::get('exam/{exam}/student', 'ExamController@student')->name('exam.show-student');
    });
});

app/Models/Student.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $guarded = ['id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function subjectStudent()
    {
        return $this->hasMany(SubjectStudent::class);
    }

    public function examStudent()
    {
        return $this->hasMany(ExamStudent::class);
    }
}

app/Http/Controllers/StudentController.php
<?php namespace App\Http\Controllers;

use TSC\Repositories\StudentRepository;
use Illuminate\Http\Request;
use App\Models\Student;
class StudentController extends Controller
{
    private $studentRepository;

    public function __construct(StudentRepository $studentRepository)
    {
        $this->studentRepository = $studentRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::with(['user'])->withCount(['subjectStudent', 'examStudent'])->paginate(10);
        return adminView('student.index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        $student->load(['user', 'subjectStudent.subjectTeacher.subject', 'subjectStudent.subjectTeacher.teacher.user', 'examStudent.exam.subjectTeacher.subject']);
        return adminView('student.show', compact('student'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        if (auth()->user()->isStudent()) {
            if (auth()->user()->student->id != $student->id) return redirect('home');
            $student->load('user');
            return studentView('profile-edit', compact('student'));
        }

        return redirect('home');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        if (auth()->user()->isStudent() && auth()->user()->student->id == $student->id) {
            $rules = [
                'name' => 'required|string|max:255',
                'email' => 'required|string|email|max:255|unique:users,id,'.$student->id,
                'student_id' => 'required|string|max:255|unique:users,id,'.$student->id,
            ];
            if (!is_null($request->password)) {
                $rules['password'] = 'required|string|min:6|confirmed';
            }
    
            $this->validate($request, $rules);
    
            $data = [
                'name' => $request->name, 
                'email' => $request->email,
                'student_id' => $request->student_id
            ];
            if (!is_null($request->password)) {
                $data['password'] = bcrypt($request->password);
            }
            $student->user->update($data);
        }

        return redirect('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        //
    }
}

resources/views/student/home.blade.php
@extends('layouts.student.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <a href="{{route('subject.index')}}" class="btn btn-primary">Subject</a>
                    <a href="{{route('exam.index')}}" class="btn btn-primary">Exams</a>
                    <a href="{{route('student.edit', auth()->user()->student->id)}}" class="btn btn-primary">Edit Profile</a>
                </div>
            </div>
        </div>

        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Notice</div>

                <div class="panel-body">
                <table class="table table-bordered table-hover table-striped table-responsive">
                        <thead>
                        <tr>
                            <th>Subject Name</th>
                            <th>Subject Code</th>
                            <th>Title</th>
                            <th>Message</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($notices as $notice)
                        <tr>
                            <td>{{$notice->subjectTeacher->subject->name}}</td>
                            <td>{{$notice->subjectTeacher->subject->code}}</td>
                            <td>{{$notice->title}}</td>
                            <td>{{$notice->message}}</td>
                        </tr>
                        @empty
                        <tr style="text-align:center;">
                            <td colspan=5><h4>No Notice Available</h4></td>
                        </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/student/profile-edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Profile Edit</div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('student.update', $student->id) }}">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="PATCH">

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') ?: $student->user->name }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') ?: $student->user->email }}" required>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('student_id') ? ' has-error' : '' }}">
                            <label for="student_id" class="col-md-4 control-label">Student ID</label>

                            <div class="col-md-6">
                                <input id="student_id" type="text" class="form-control" name="student_id" value="{{ old('student_id') ?: $student->user->student_id }}" required>

                                @if ($errors->has('student_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('student_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password">

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Update Profile
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection