routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'web', 'prefix' => '/'], function () {
    Auth::routes();
    Route::group(['middleware' => 'auth'], function() {
        Route::get('home', 'HomeController@index')->name('home');
        Route::resource('subject', 'SubjectController');
        Route::get('subject/student-list/{subject}', 'SubjectController@studentList')->name('subject.student-list');
        Route::resource('enroll-request', 'EnrollRequestController');
        Route::resource('exam', 'ExamController');
        Route::get('exam/change-status/{exam}', 'ExamController@changeStatus')->name('exam.change-status');
        Route::resource('notice', 'NoticeController');
        Route::resource('student', 'StudentController');
    });

    Route::group(['middleware' => 'admin_auth'], function () {
        Route::resource('teacher', 'TeacherController');
        Route::post('subject/{subject}/assign-teacher', 'SubjectController@assignTeacher');
    });

    Route::group(['middleware' => 'student_auth'], function () {
        Route::get('unenrolled-subjects', 'SubjectController@unenrolledSubjects')->name('unenrolled-subjects');
        Route::get('take-exam/{exam}', 'ExamController@takeExam')->name('exam.take-exam');
        Route::post('store-answer/{exam}', 'ExamController@storeAnswer')->name('exam.store-answer');
    });

    Route::group(['middleware' => 'teacher_auth'], function () {
        Route::resource('exam-question', 'ExamQuestionController');
        Route::get('exam/{exam}/student', 'ExamController@student')->name('exam.show-student');
    });
});

app/Models/Subject.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    protected $guarded = ['id'];

    public function teacher()
    {
        return $this->belongsToMany(Teacher::class);
    }

    public function subjectTeacher()
    {
        return $this->hasMany(SubjectTeacher::class);
    }

    public function subjectStudent()
    {
        return $this->hasManyThrough(SubjectStudent::class, SubjectTeacher::class);
    }
}

app/Http/Controllers/SubjectController.php
<?php namespace App\Http\Controllers;

use App\Models\Subject;
use App\Models\Teacher;
use App\Models\SubjectStudent;
use App\Models\SubjectTeacher;
use Illuminate\Http\Request;

class SubjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (auth()->user()->isAdmin()) {
            $subjects = Subject::withCount('teacher')->paginate(10);
            return adminView('subject.index', compact('subjects'));
        } elseif (auth()->user()->isStudent()) {
            $subjects = SubjectStudent::with('subjectTeacher.subject', 'subjectTeacher.teacher.user')->paginate(10);            
            return studentView('subject.index', compact('subjects'));
        } elseif (auth()->user()->isTeacher()) {
            $teacher = auth()->user()->teacher;
            $subjects = $teacher->load(['subjectTeacher' => function($query) {
                return $query->with('subject')->withCount('subjectStudent');
            }])->subjectTeacher;
            return teacherView('subject.index', compact('subjects'));
        }
        
        return redirect('home');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return adminView('subject.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|min:6',
            'code' => 'required|unique:subjects|min:4'
        ]);
        $subject = Subject::create([
            'name' => $request->name,
            'code' => $request->code
        ]);
        return redirect()->route('subject.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function show(Subject $subject)
    {
        if (auth()->user()->isAdmin()) {
            return $this->showForAdmin($subject);
        }
        return redirect('home');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function edit(Subject $subject)
    {
        return adminView('subject.edit', compact('subject'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Subject  $subject
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Subject $subject)
    {
        $this->validate($request, [
            'name' => 'required|string|min:6',
            'code' => "required|unique:subjects,code,$subject->id|min:4"
        ]);
        $subject->update([
            'name' => $request->name,
            'code' => $request->code
        ]);
        return redirect()->route('subject.index');
    }

    public function assignTeacher(Subject $subject, Request $request)
    {
        if ($request->has('teacher')) {
            $subject->teacher()->sync($request->teacher);
            return 1;
        }
        return 0;
    }

    private function showForAdmin(Subject $subject)
    {
        $subject = $subject->load(['teacher' => function ($query) {
            return $query->withCount('subjectStudent')->with('user');
        }]);
        $teachers = Teacher::with('user')->doesntHave('subjectTeacher', 'and', function($query) use ($subject) {
            return $query->where('subject_id', $subject->id)->toSql();
        })->get();
        return adminView('subject.show', compact('subject', 'teachers'));
    }

    public function unenrolledSubjects()
    {
        $student = auth()->user()->student;
        $subjects = Subject::doesntHave('subjectStudent', 'and', function($query) use ($student) {
            return $query->where('student_id', $student->id);
        })->with('subjectTeacher.teacher.user')->get();
        return studentView('subject.enroll', compact('subjects'));
    }

    public function studentList(SubjectTeacher $subject)
    {
        if (auth()->user()->isTeacher()) {
            $subject->load('subjectStudent.student.user', 'subject');
            return teacherView('subject.student-list', compact('subject'));
        }
        return redirect('home');
    }
}

resources/views/admin/subject/_assign_teacher.blade.php
<div class="col-md-8">
    <div class="form-group">
        <label>Subject Name:</label>
        <select id="selected_teacher" class="form-control">
            
        </select>
        @if ($errors->has('name'))
            <span class="help-block">
                <strong class="text-danger">{{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="col-md-4">
    <button class="btn btn-primary" style="margin-top:12%;" id="teacher_assign_button">Assign</button>
</div>
@push('other_scripts')
<script>
    var teacher_assign_url = '{{ env("APP_URL")."/subject/$subject->id/assign-teacher" }}';
    var csrf_token = '{{ csrf_token() }}';

    function updateTeacherDropdown()
    {
        $('#selected_teacher').html('');
        teachers.map((teacher) => {
            $('#selected_teacher').append(`<option value="${teacher.id}">${teacher.user.name}</option>`);
        });
    }
    updateTeacherDropdown();

    $('#teacher_assign_button').click(function() {
        let selected_teacher_id = $('#selected_teacher').val();
        let selected_teacher = [selected_teacher_id].concat(assigned_teacher_ids);
        jQuery.ajax({
            type:"post",
            dataType:"json",
            url: teacher_assign_url,
            data: {_token: csrf_token, teacher: selected_teacher},
            success: function(data) {
                if (data) {
                    assigned_teacher_ids.push(selected_teacher_id);
                    teachers = teachers.filter(function (teacher) {
                        return teacher.id != selected_teacher_id;
                    });
                    updateTeacherDropdown();
                }
            },
            error: function(data) {
                
            },
        });
    });
</script>
@endpush

resources/views/admin/subject/_teacher_table.blade.php
<table class="table table-bordered table-hover table-striped">
    <thead>
    <tr>
        <th>ID.</th>
        <th>Name</th>
        <th>Email</th>
        <th>Number of Students</th>
    </tr>
    </thead>
    <tbody id="assigned_teacher_table">
    @forelse($teachers as $teacher)
    <?php $user = $teacher->user ?>
    <tr>
        <td>{{$teacher->id}}</td>
        <td>{{$user->name}}</td>
        <td>{{$user->email}}</td>
        <td>{{$teacher->subject_student_count}}</td>
    </tr>
    @empty
    <tr style="text-align:center;">
        <td colspan=5><h4>No Teacher Available</h4></td>
    </tr>
    @endforelse
    </tbody>
</table>

resources/views/admin/subject/create.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Subject Create</h3>
                </div>

                <div class="panel-body">
                    <form action="{{ route('subject.store') }}" method="POST">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label>Subject Name:</label>
                            <input type="input" class="form-control" name="name" value="{{ old('name') }}" required>
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label>Subject Code:</label>
                            <input type="input" class="form-control" name="code" value="{{ old('code') }}" required>
                            @if ($errors->has('code'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('code') }}</strong>
                                </span>
                            @endif
                        </div>

                        <input type="submit" class="btn btn-primary" value="Add Subject">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/subject/edit.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4>Subject Create</h3>
                </div>

                <div class="panel-body">
                    <form action="{{ route('subject.update', $subject->id) }}" method="POST">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="PUT">
                        <div class="form-group">
                            <label>Subject Name:</label>
                            <input type="input" class="form-control" name="name" value="{{ old('name') ?: $subject->name }}" required>
                            @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('name') }}</strong>
                                </span>
                            @endif
                        </div>

                        <div class="form-group">
                            <label>Subject Code:</label>
                            <input type="input" class="form-control" name="code" value="{{ old('code') ?: $subject->code}}" required>
                            @if ($errors->has('code'))
                                <span class="help-block">
                                    <strong class="text-danger">{{ $errors->first('code') }}</strong>
                                </span>
                            @endif
                        </div>

                        <input type="submit" class="btn btn-primary" value="Edit Subject">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/subject/index.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 style="display:inline;">Subject List</h3>
                    <a href="{{ route('subject.create') }}" class="btn btn-primary pull-right">Add</a>
                </div>

                <div class="panel-body">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                        <tr>
                            <th>ID.</th>
                            <th>Name</th>
                            <th>Code</th>
                            <th>Number of Teacher</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($subjects as $subject)
                        <tr>
                            <td>{{$subject->id}}</td>
                            <td>{{$subject->name}}</td>
                            <td>{{$subject->code}}</td>
                            <td>{{$subject->teacher_count}}</td>
                            <td>
                                <a href="{{ route('subject.show', $subject->id) }}" class="btn btn-success">Detail</a>
                                <a href="{{ route('subject.edit', $subject->id) }}" class="btn btn-default">Edit</a>
                            </td>
                        </tr>
                        @empty
                        <tr style="text-align:center;">
                            <td colspan=5><h4>No Subject Available</h4></td>
                        </tr>
                        @endforelse
                        </tbody>
                    </table>
                    {{ $subjects->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/subject/show.blade.php
@extends('layouts.admin.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 style="display:inline;">Subject Details</h3>
                </div>

                <div class="panel-body">
                    <h4>Name: {{ $subject->name }}</h4>
                    <h4>Code: <code>{{ $subject->code }}</code></h4>
                </div>
            </div>
        </div>

        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 style="display:inline;">Assigned Teachers to {{ $subject->name }}</h3>
                </div>

                <div class="panel-body">
                    @include('admin.subject._teacher_table', ['teachers' => $subject->teacher])
                </div>
            </div>
        </div>

        @if ($teachers->count())
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 style="display:inline;">Assigne Teacher to {{ $subject->name }}</h3>
                </div>

                <div class="panel-body">
                    @include('admin.subject._assign_teacher', ['teachers' => $teachers, 'subject' => $subject])
                </div>
            </div>
        </div>
        @endif
    </div>
</div>
@endsection

@section('scripts')
<script>
    var teachers = JSON.parse('{!! addslashes(json_encode($teachers)) !!}');
    var assigned_teacher_ids = JSON.parse('{!! addslashes(json_encode($subject->teacher->pluck('id')->toArray())) !!}');
</script>
@stack('other_scripts')
@endsection